/**
 * Build script: embed all .cube LUT files into luts-embedded.js
 * This allows the LUT feature to work under file:// protocol
 * where XHR/fetch is blocked by browser security policy.
 *
 * Usage: node tools/embed-luts.js
 */
var fs = require('fs');
var path = require('path');

var LUTS_DIR = path.join(__dirname, '..', 'luts');
var OUTPUT = path.join(__dirname, '..', 'luts-embedded.js');

var EMBEDDED = {};

function walkDir(dir) {
  var entries = fs.readdirSync(dir, { withFileTypes: true });
  entries.forEach(function(entry) {
    var full = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      walkDir(full);
    } else if (entry.name.endsWith('.cube')) {
      var relPath = path.relative(path.join(__dirname, '..'), full);
      // Normalize to forward slashes
      relPath = relPath.split(path.sep).join('/');
      parseAndEmbed(full, relPath);
    }
  });
}

function parseCubeText(text) {
  var lines = text.split('\n');
  var size = 0;
  var dataLines = [];

  for (var i = 0; i < lines.length; i++) {
    var line = lines[i].trim();
    if (line.length === 0 || line.charAt(0) === '#') continue;

    if (line.indexOf('LUT_3D_SIZE') === 0) {
      size = parseInt(line.split(/\s+/)[1], 10);
      continue;
    }

    if (line.indexOf('LUT_3D_INPUT_RANGE') === 0) continue;
    if (line.indexOf('DOMAIN_') === 0) continue;

    var parts = line.split(/\s+/);
    if (parts.length >= 3) {
      var r = parseFloat(parts[0]);
      var g = parseFloat(parts[1]);
      var b = parseFloat(parts[2]);
      if (!isNaN(r) && !isNaN(g) && !isNaN(b)) {
        dataLines.push(r, g, b);
      }
    }
  }

  if (size < 2) throw new Error('Invalid LUT: size must be >= 2');
  var expected = size * size * size * 3;
  if (dataLines.length !== expected) {
    throw new Error('Invalid LUT data: expected ' + expected + ' values, got ' + dataLines.length);
  }

  return { size: size, data: dataLines };
}

function parseAndEmbed(filePath, relPath) {
  console.log('Processing:', relPath);
  var text = fs.readFileSync(filePath, 'utf-8');
  var lut = parseCubeText(text);

  var float32Array = new Float32Array(lut.data);
  var buffer = Buffer.from(float32Array.buffer);
  var base64 = buffer.toString('base64');

  EMBEDDED[relPath] = { size: lut.size, data: base64 };
  console.log('  -> ' + relPath + ' (' + (buffer.length / 1024).toFixed(0) + 'KB, base64: ' + (base64.length / 1024).toFixed(0) + 'KB)');
}

function generate() {
  walkDir(LUTS_DIR);

  var keys = Object.keys(EMBEDDED);
  console.log('\nTotal LUTs embedded:', keys.length);

  var lines = [];
  lines.push('// Auto-generated by tools/embed-luts.js');
  lines.push('// Contains all .cube LUT data as base64-encoded Float32Array buffers');
  lines.push('// This enables LUT support under file:// protocol');
  lines.push('(function(){');
  lines.push('var data = {};');

  keys.forEach(function(key) {
    var lut = EMBEDDED[key];
    lines.push('data[' + JSON.stringify(key) + '] = { size: ' + lut.size + ', data: ' + JSON.stringify(lut.data) + ' };');
  });

  lines.push('window.__LUT_EMBEDDED = data;');
  lines.push('})();');

  var output = lines.join('\n');
  fs.writeFileSync(OUTPUT, output, 'utf-8');

  var totalSizeKB = (Buffer.byteLength(output, 'utf-8') / 1024).toFixed(0);
  console.log('\nWritten to: ' + OUTPUT);
  console.log('Output size: ' + totalSizeKB + 'KB');
}

generate();
